// Generated by CIRCT 4c9e8334a

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module traffic_light_fsm_circt(	// traffic_light_fsm.mlir:2:3
  input        clk,	// traffic_light_fsm.mlir:2:35
               reset,	// traffic_light_fsm.mlir:2:49
  output [1:0] state,	// traffic_light_fsm.mlir:2:66
  output       red,	// traffic_light_fsm.mlir:2:82
               yellow,	// traffic_light_fsm.mlir:2:96
               green	// traffic_light_fsm.mlir:2:113
);

  wire [1:0] _GEN;	// traffic_light_fsm.mlir:33:11
  reg  [2:0] timer;	// traffic_light_fsm.mlir:17:14
  reg  [1:0] current_state;	// traffic_light_fsm.mlir:16:22
  wire       _GEN_0 = current_state === 2'h0;	// traffic_light_fsm.mlir:11:14, :16:22, :18:10
  wire       _GEN_1 = current_state === 2'h1;	// traffic_light_fsm.mlir:7:14, :16:22, :19:10
  wire       _GEN_2 = current_state === 2'h2;	// traffic_light_fsm.mlir:5:15, :16:22, :20:10
  wire       _GEN_3 = ~_GEN_0;	// traffic_light_fsm.mlir:18:10, :21:10
  wire       _GEN_4 = ~_GEN_1;	// traffic_light_fsm.mlir:19:10, :22:10
  wire       _GEN_5 = _GEN_4 & _GEN_3 & _GEN_2;	// traffic_light_fsm.mlir:20:10, :21:10, :22:10, :23:10
  wire       _GEN_6 = _GEN_3 & _GEN_1;	// traffic_light_fsm.mlir:19:10, :21:10, :27:11
  assign _GEN =
    _GEN_5 | _GEN_6 | _GEN_0
      ? (timer == (_GEN_6 ? 3'h3 : _GEN_5 ? 3'h1 : 3'h2)
           ? (_GEN_6 ? 2'h2 : {1'h0, ~_GEN_5})
           : current_state)
      : 2'h0;	// traffic_light_fsm.mlir:4:14, :5:15, :6:14, :8:14, :9:14, :11:14, :16:22, :17:14, :18:10, :23:10, :24:11, :25:11, :26:11, :27:11, :28:11, :29:11, :30:11, :31:11, :32:11, :33:11
  wire       _GEN_7 = current_state !== 2'h0;	// traffic_light_fsm.mlir:11:14, :16:22, :35:11
  wire       _GEN_8 = _GEN_4 & _GEN_7;	// traffic_light_fsm.mlir:22:10, :35:11, :36:11
  wire       _GEN_9 = _GEN_7 & _GEN_1;	// traffic_light_fsm.mlir:19:10, :35:11, :39:11
  wire       _GEN_10 = ~_GEN_9;	// traffic_light_fsm.mlir:39:11, :40:11
  always @(posedge clk or posedge reset) begin	// traffic_light_fsm.mlir:15:10
    if (reset) begin	// traffic_light_fsm.mlir:15:10
      current_state <= 2'h0;	// traffic_light_fsm.mlir:11:14, :16:22
      timer <= 3'h0;	// traffic_light_fsm.mlir:10:14, :17:14
    end
    else begin	// traffic_light_fsm.mlir:15:10
      current_state <= _GEN;	// traffic_light_fsm.mlir:16:22, :33:11
      timer <= current_state == _GEN ? timer + 3'h1 : 3'h0;	// traffic_light_fsm.mlir:9:14, :10:14, :12:10, :13:10, :14:10, :16:22, :17:14, :33:11
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// traffic_light_fsm.mlir:2:3
    `ifdef FIRRTL_BEFORE_INITIAL	// traffic_light_fsm.mlir:2:3
      `FIRRTL_BEFORE_INITIAL	// traffic_light_fsm.mlir:2:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// traffic_light_fsm.mlir:2:3
      automatic logic [31:0] _RANDOM[0:0];	// traffic_light_fsm.mlir:2:3
      `ifdef INIT_RANDOM_PROLOG_	// traffic_light_fsm.mlir:2:3
        `INIT_RANDOM_PROLOG_	// traffic_light_fsm.mlir:2:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// traffic_light_fsm.mlir:2:3
        for (logic  i = 1'h0; i < 1'h1; i += 1'h1) begin
          _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// traffic_light_fsm.mlir:2:3
        end	// traffic_light_fsm.mlir:2:3
        current_state = _RANDOM[/*Zero width*/ 1'b0][1:0];	// traffic_light_fsm.mlir:2:3, :16:22
        timer = _RANDOM[/*Zero width*/ 1'b0][4:2];	// traffic_light_fsm.mlir:2:3, :17:14
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin	// traffic_light_fsm.mlir:2:3
        current_state = 2'h0;	// traffic_light_fsm.mlir:11:14, :16:22
        timer = 3'h0;	// traffic_light_fsm.mlir:10:14, :17:14
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// traffic_light_fsm.mlir:2:3
      `FIRRTL_AFTER_INITIAL	// traffic_light_fsm.mlir:2:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign state = current_state;	// traffic_light_fsm.mlir:16:22, :43:5
  assign red = _GEN_10 & (~_GEN_8 | ~_GEN_2);	// traffic_light_fsm.mlir:20:10, :34:11, :36:11, :37:11, :38:11, :40:11, :41:11, :43:5
  assign yellow = _GEN_10 & _GEN_8 & _GEN_2;	// traffic_light_fsm.mlir:20:10, :36:11, :40:11, :42:11, :43:5
  assign green = _GEN_9;	// traffic_light_fsm.mlir:39:11, :43:5
endmodule
