// Generated by CIRCT 4c9e8334a

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module counter_circt(	// counter.mlir:2:3
  input        clk,	// counter.mlir:2:25
               reset,	// counter.mlir:2:39
  output [7:0] count	// counter.mlir:2:56
);

  reg [7:0] count_0;	// counter.mlir:7:14
  always @(posedge clk or posedge reset) begin	// counter.mlir:6:10
    if (reset)	// counter.mlir:6:10
      count_0 <= 8'h0;	// counter.mlir:4:14, :7:14
    else	// counter.mlir:6:10
      count_0 <= count_0 + 8'h1;	// counter.mlir:3:14, :5:10, :7:14
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_	// counter.mlir:2:3
    `ifdef FIRRTL_BEFORE_INITIAL	// counter.mlir:2:3
      `FIRRTL_BEFORE_INITIAL	// counter.mlir:2:3
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// counter.mlir:2:3
      automatic logic [31:0] _RANDOM[0:0];	// counter.mlir:2:3
      `ifdef INIT_RANDOM_PROLOG_	// counter.mlir:2:3
        `INIT_RANDOM_PROLOG_	// counter.mlir:2:3
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// counter.mlir:2:3
        for (logic  i = 1'h0; i < 1'h1; i += 1'h1) begin
          _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// counter.mlir:2:3
        end	// counter.mlir:2:3
        count_0 = _RANDOM[/*Zero width*/ 1'b0][7:0];	// counter.mlir:2:3, :7:14
      `endif // RANDOMIZE_REG_INIT
      if (reset)	// counter.mlir:2:3
        count_0 = 8'h0;	// counter.mlir:4:14, :7:14
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// counter.mlir:2:3
      `FIRRTL_AFTER_INITIAL	// counter.mlir:2:3
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign count = count_0;	// counter.mlir:7:14, :8:5
endmodule
